#!/usr/bin/env python

import sys
import rospy
import moveit_commander
import geometry_msgs

class main:
    
    def __init__(self):

        moveit_commander.roscpp_initialize(sys.argv)

        self.robot_name = "panda_arm"
        self.robot_group = moveit_commander.MoveGroupCommander(self.robot_name)
        self.gripper_name = "hand"
        self.gripper_group = moveit_commander.MoveGroupCommander(self.gripper_name)

        self.scene = moveit_commander.PlanningSceneInterface()

        rospy.sleep(5)

        self.go_to_extended()

        # self.go_to_random()

        self.open_gripper()

        self.close_gripper()

    def go_to_random(self):
        pose = geometry_msgs.msg.Pose()
        pose.position.x = -0.0686
        pose.position.y = 0.22654
        pose.position.z = 1.0141
        pose.orientation.x = -0.09
        pose.orientation.y = 0.82774
        pose.orientation.z = -0.059948
        pose.orientation.w = 0.055058
        self.robot_group.go(pose, wait="true")
        self.robot_group.stop()

    def go_to_extended(self):

        self.robot_group.set_named_target('extended')
        self.robot_group.go()
        self.robot_group.stop()

    def close_gripper(self):

        self.gripper_group.set_named_target('close')
        self.gripper_group.go()
        self.gripper_group.stop()

    def open_gripper(self):

        self.gripper_group.set_named_target('open')
        self.gripper_group.go()
        self.gripper_group.stop()
        
if __name__ == '__main__':
    rospy.init_node('send_commands')
    main = main()
    rospy.spin()