#!/usr/bin/env python

import rospy
import sys
import moveit_commander

class ManipulatorControl:
    def __init__(self):
        # initialize moveit commander
        moveit_commander.roscpp_initialize(sys.argv)

    
def main():
    """
    the main() function
    """
    rospy.init_node('manipulator')
    node = ManipulatorControl()
    rospy.spin()

if __name__ == '__main__':
    try:
        main()
    except rospy.ROSInterruptException:
        pass